name: SENATOROV
on:
  push:
    branches:
      - '**'

  schedule:
    - cron: '0 0 * * *' # Run every day
  workflow_dispatch:
  create:
  delete:
  release:
  issues:

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isort/isort-action@v1
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
          isort-version: 5.13.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort nbqa
      - name: isort
        run: |
          nbqa isort --float-to-top $(git ls-files '*.ipynb')
          isort --float-to-top $(git ls-files '*.py')
      - name: Commit and push changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}
          git pull origin ${{ github.ref_name }}
          git add .
          git diff --quiet || (git commit -m "Sort imports and apply isort fixes" && git push origin ${{ github.ref_name }})
